# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    version: '3.1.401'
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    version: '3.1.401'
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  displayName: 'dotnet test $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    version: '3.1.401'
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
  displayName: 'dotnet publish $(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/BenITHome/bin/Release/net5.0/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(buildConfiguration).zip'
    replaceExistingArchive: true
  displayName: 'ArchiveFile $(buildConfiguration)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '免費試用版(c598e038-deed-49f3-bbbe-a9bcfd56ea1f)'
    subscriptionId: 'c598e038-deed-49f3-bbbe-a9bcfd56ea1f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzurePipelineRG'
    location: 'East Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.prod.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    displayName: 'Azure Resource Manager'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '免費試用版(c598e038-deed-49f3-bbbe-a9bcfd56ea1f)'
    appType: 'webAppLinux'
    appName: 'contosowebapppjzohlzgqaho4'
    package: '$(System.DefaultWorkingDirectory)/$(buildConfiguration).zip'
    runtimeStack: 'DOTNET|5.0'
    startUpCommand: 'dotnet BenITHome.dll'
  displayName: 'Azure WebApp deploy $(buildConfiguration)'